import { library } from "@fortawesome/fontawesome-svg-core";
import {
	faChevronLeft,
	faPlus,
	faMinus,
	faTh,
	faChevronRight,
	faChevronDown,
	faChevronUp,
	faUser,
	faUnlock,
	faCircleNotch,
	faLongArrowAltRight,
	faLongArrowAltLeft,
	faRedoAlt,
	faSearch,
	faSignOutAlt,
	faEnvelope,
	faEllipsisV,
	faPencilAlt,
	faFile,
	faHome,
	faCalendarAlt,
	faThumbtack,
	faHeart,
	faStar,
	faTrashAlt,
	faStarHalfAlt,
	faEyeSlash,
	faLockOpen,
	faCheck,
	faArrowUp,
	faArrowDown
} from "@fortawesome/free-solid-svg-icons";

const initializeFontAwesome = () =>
	library.add(
		faChevronLeft,
		faPlus,
		faMinus,
		faTh,
		faChevronRight,
		faUser,
		faUnlock,
		faCircleNotch,
		faLongArrowAltRight,
		faLongArrowAltLeft,
		faRedoAlt,
		faChevronDown,
		faChevronUp,
		faSearch,
		faSignOutAlt,
		faEnvelope,
		faEllipsisV,
		faPencilAlt,
		faFile,
		faHome,
		faCalendarAlt,
		faThumbtack,
		faHeart,
		faStar,
		faTrashAlt,
		faStarHalfAlt,
		faEyeSlash,
		faLockOpen,
		faCheck,
		faArrowUp,
		faArrowDown
	);

export default initializeFontAwesome;
